# 20260731
name:  build-test-deploy

on: 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # workflow_dispatch: {}
  # schedule:
  #   - cron: "27 12,13 * * *"
  #     timezone: "Europe/Warsaw"

jobs:
  build-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app1  # all 'run' steps use this directory
    steps:
      - name:  check out of repo
        uses: actions/checkout@v4

      - name: use node.js
        uses: actions/setup-node@v4
        with: 
          node-revision: '24.x'

      - name: Install dependencies
        run:  npm install 

      - name: Build the application
        run: npm run build

  # test-job:
  #   needs: build-job
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #         working-directory: ./app1  # all 'run' steps use this directory
  #   steps:
  #     - name:  check out of repo
  #       uses: actions/checkout@v4
        
  #     - name: use node.js
  #       uses: actions/setup-node@v4
  #       with: 
  #         node-revision: '20.x'
  #     - run:  npm install
  #     - run:  |
  #         cd ./app1
  #         npm test

  deploy-job:
    needs: build-job
    permissions: 
      contents: write
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./app1  # all 'run' steps use this directory
    steps:
      - name:  check out of repo
        uses: actions/checkout@v4
        with: 
          token: ${{secrets.GITHUB_TOKEN}}
      - name: use node.js
        uses: actions/setup-node@v4      
        with: 
          node-revision: '24.x'

      - name: configure github pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run:  npm install 

      - name: Build the application
        run: npm run build
      
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/app/'
  
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
    

