# 20260731
name:  build-test-deploy

on: 
  workflow_dispatch: {}
  schedule:
    - cron: "27 12,13 * * *"
      timezone: "Europe/Warsaw"

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name:  check out of repo
        uses: actions/checkout@v4
        
      - name: use node.js
        uses: actions/setup-node@v4
        with: 
          node-revision: '20.x'
      - run: npm install --prefix ./app1/
      - run: npm run build --prefix ./app1/

  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name:  check out of repo
        uses: actions/checkout@v4
        
      - name: use node.js
        uses: actions/setup-node@v4
        with: 
          node-revision: '20.x'
      - run:  npm install
      - run:  |
          cd ./app1
          npm test

  deploy-job:
    needs: test-job
    permissions: 
      contents: write
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name:  check out of repo
        uses: actions/checkout@v4
        with: 
          token: ${{secrets.GITHUB_TOKEN}}
      - name: use node.js
        uses: actions/setup-node@v4      
        with: 
          node-revision: '20.x'

      - name: configure github pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - run: npm install
      - run: |
          cd ./app1
          npm run build
      
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './app1/dist/app/browser'
  
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
    

