# 20260731
name:  build-test-deploy

on: push

jobs:
  build:
    runs-on: ubintu-latest
    steps:
      - name:  check out of repository
        uses: actions/checkout@v4
        
      - name: use node.js
        uses: actions/setup-node@v4
        with: 
          node-revision: '20.x'
      - run:  npm install
      - run:  npm run build

  test:
    needs: build
    runs-on: ubintu-latest
    steps:
      - name:  check out of repository
        uses: actions/checkout@v4
        
      - name: use node.js
        uses: actions/setup-node@v4
        with: 
          node-revision: '20.x'
      - run:  npm install
      - run:  npm test

  deploy:
    needs: test
    permissions: 
      contents: write
      pages: write
      id-token: write
    environment: production

